//! Static initializers. `__sinit_<file>_cpp` is generated by the compiler from the dynamic
//! initializations of the unit's globals, in definition order: constructor calls (plus
//! `__register_global_object` for destructors), stores of computed values, and the member stores
//! of inlined constructors. Its draft is therefore not a function but those definitions:
//! `T g(args);` / `T g = value;`. Globals the context doesn't declare (file-local objects) get a
//! stand-in class with a constructor taking each stored member.

use super::*;
use std::collections::HashMap;

enum Init {
    Ctor { sig: mwdec_core::FuncSig, args: Vec<Expr> },
    Value(Expr),
    /// (offset, access type, value) per stored member
    Fields(Vec<(i32, Type, Expr)>),
}

struct G {
    symbol: String,
    /// the IR's type for the global as a whole (its extent when the context doesn't declare it)
    ty: Type,
    init: Init,
    registered: bool,
    /// class of the destructor registered for it (its type, when the context doesn't say)
    dtor_class: Option<String>,
}

/// (global symbol, byte offset) a pointer expression points at.
fn global_ptr(e: &Expr) -> Option<(String, Type, i32)> {
    match e {
        Expr::AddrOf(x) => global_lvalue(x).map(|(s, t, o, _)| (s, t, o)),
        Expr::Cast { e, .. } => global_ptr(e),
        // an untyped buffer's name is its address
        Expr::Global { symbol, ty } => Some((symbol.clone(), ty.clone(), 0)),
        _ => None,
    }
}

/// (global symbol, its type, offset, access type) of an lvalue inside a global.
fn global_lvalue(e: &Expr) -> Option<(String, Type, i32, Type)> {
    match e {
        Expr::Global { symbol, ty } => Some((symbol.clone(), ty.clone(), 0, ty.clone())),
        Expr::Member { base, offset, ty } => global_lvalue(base).map(|(s, gt, o, _)| (s, gt, o + offset, ty.clone())),
        Expr::Load { base, offset, ty } => global_ptr(base).map(|(s, gt, o)| (s, gt, o + offset, ty.clone())),
        _ => None,
    }
}

impl<'a> Em<'a> {
    /// The definitions a static initializer comes from, or None when its body has a shape this
    /// doesn't handle.
    pub(crate) fn sinit_defs(&mut self) -> Option<String> {
        let ir = self.ir;
        if !ir.symbol.starts_with("__sinit_") || self.opts.c_mode {
            return None;
        }
        let db = self.db?;
        // single-definition register locals are inlined into the values
        let mut defs: HashMap<VarId, Expr> = HashMap::new();
        let mut ndefs: HashMap<VarId, usize> = HashMap::new();
        for s in &ir.body {
            match s {
                // (register locals and stack spill slots)
                Stmt::Assign { dst: Expr::Var(v), src } if matches!(ir.vars[*v].kind, VarKind::Local | VarKind::Stack { .. }) => {
                    *ndefs.entry(*v).or_default() += 1;
                    defs.insert(*v, src.clone());
                }
                // a stack temporary constructed in place: the temporary object `T(args)`
                Stmt::Expr(Expr::Call { callee: Callee::Method { sig: cs, this, .. }, args, .. }) if sig::is_ctor(cs) && matches!(&**this, Expr::AddrOf(x) if matches!(&**x, Expr::Var(v) if matches!(ir.vars[*v].kind, VarKind::Stack { .. }))) => {
                    let Expr::AddrOf(x) = &**this else { unreachable!() };
                    let Expr::Var(v) = &**x else { unreachable!() };
                    *ndefs.entry(*v).or_default() += 1;
                    defs.insert(*v, Expr::Construct { class: Type::Named(cs.this_class.clone()?), ctor: Some(cs.clone()), args: args.clone() });
                }
                Stmt::Assign { .. } | Stmt::Expr(_) | Stmt::Return(None) | Stmt::Comment(_) => {}
                _ => return None,
            }
        }
        if ndefs.values().any(|&n| n > 1) {
            return None;
        }
        fn subst(e: &Expr, defs: &HashMap<VarId, Expr>, depth: u32) -> Option<Expr> {
            if depth > 8 {
                return None;
            }
            let mut out = e.clone();
            let mut ok = true;
            out.rewrite(&mut |x| {
                if let Expr::Var(v) = x {
                    match defs.get(v).map(|d| subst(d, defs, depth + 1)) {
                        Some(Some(r)) => *x = r,
                        _ => ok = false,
                    }
                }
            });
            ok.then_some(out)
        }
        let mut gs: Vec<G> = vec![];
        let at = |gs: &mut Vec<G>, sym: &str, ty: &Type, init: Init| -> Option<()> {
            match gs.iter_mut().find(|g| g.symbol == sym) {
                None => {
                    gs.push(G { symbol: sym.to_string(), ty: ty.clone(), init, registered: false, dtor_class: None });
                    Some(())
                }
                Some(g) => match (&mut g.init, init) {
                    (Init::Fields(fs), Init::Fields(mut more)) => {
                        fs.append(&mut more);
                        Some(())
                    }
                    _ => None,
                },
            }
        };
        for s in &ir.body {
            match s {
                Stmt::Assign { dst: Expr::Var(_), .. } | Stmt::Return(None) | Stmt::Comment(_) => {}
                Stmt::Expr(Expr::Call { callee: Callee::Method { this, .. }, .. }) if matches!(&**this, Expr::AddrOf(x) if matches!(&**x, Expr::Var(v) if defs.contains_key(v))) => {}
                Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) if symbol == "__register_global_object" => {
                    let (g, _, _) = args.first().and_then(global_ptr)?;
                    fn func_addr(e: &Expr) -> Option<&str> {
                        match e {
                            Expr::FuncAddr { symbol } => Some(symbol),
                            Expr::Cast { e, .. } => func_addr(e),
                            _ => None,
                        }
                    }
                    let dc = args.get(1).and_then(func_addr).filter(|s| s.starts_with("__dt__")).and_then(|s| sig::sig_of(s, Some(db)).this_class);
                    let x = gs.iter_mut().find(|x| x.symbol == g)?;
                    x.registered = true;
                    x.dtor_class = dc;
                }
                Stmt::Expr(Expr::Call { callee: Callee::Method { sig: ms, this, .. }, args, .. }) => {
                    let (g, gt, off) = global_ptr(this)?;
                    let args: Vec<Expr> = args.iter().map(|a| subst(a, &defs, 0)).collect::<Option<_>>()?;
                    if sig::is_ctor(ms) && off == 0 {
                        at(&mut gs, &g, &gt, Init::Ctor { sig: ms.clone(), args })?;
                    } else {
                        // an inline setter (`SetX(v)`: `mX = x ;`): a member store
                        let cls = ms.this_class.clone()?;
                        let (foff, fty) = self.setter_field(&cls, ms, args.len())?;
                        at(&mut gs, &g, &gt, Init::Fields(vec![(off + foff, fty, args[0].clone())]))?;
                    }
                }
                Stmt::Assign { dst, src } => {
                    let (g, gt, off, ty) = global_lvalue(dst)?;
                    let v = subst(src, &defs, 0)?;
                    // (a store of the whole global is a store at offset 0 too: it may be the
                    // first member of an object, `*(float*)&v = x`)
                    let gt = if matches!(dst, Expr::Global { .. }) { self.gtypes.get(&g).cloned().unwrap_or(gt) } else { gt };
                    at(&mut gs, &g, &gt, Init::Fields(vec![(off, ty, v)]))?;
                }
                _ => return None,
            }
        }
        if gs.is_empty() {
            return None;
        }
        // a value reading another global defined here that the context doesn't declare would
        // need a declaration before its definition
        let defined: Vec<String> = gs.iter().map(|g| g.symbol.clone()).collect();
        let mut reads_own = false;
        for g in &gs {
            let vals: Vec<&Expr> = match &g.init {
                Init::Ctor { args, .. } => args.iter().collect(),
                Init::Value(v) => vec![v],
                Init::Fields(fs) => fs.iter().map(|(_, _, v)| v).collect(),
            };
            for v in vals {
                v.walk(&mut |x| {
                    if let Expr::Global { symbol, .. } = x {
                        if defined.contains(symbol) && !db.globals.contains_key(symbol) {
                            reads_own = true;
                        }
                    }
                });
            }
        }
        if reads_own {
            return None;
        }
        // definition order: the compiler's stores of one object end in definition order (the
        // first stores of several objects may be scheduled together)
        let mut last: HashMap<String, usize> = HashMap::new();
        for (i, s) in ir.body.iter().enumerate() {
            Stmt::walk_exprs(std::slice::from_ref(s), &mut |x| {
                if let Expr::Global { symbol, .. } = x {
                    last.insert(symbol.clone(), i);
                }
            });
        }
        gs.sort_by_key(|g| last.get(&g.symbol).copied().unwrap_or(0));
        let mut out = String::new();
        for (k, g) in gs.iter().enumerate() {
            let d = self.sinit_def(g, k)?;
            out.push_str(&d);
            out.push('\n');
        }
        Some(out)
    }

    /// The member an inline setter of `cls` stores its argument into: (offset, type).
    fn setter_field(&self, cls: &str, ms: &mwdec_core::FuncSig, nargs: usize) -> Option<(i32, Type)> {
        let db = self.db?;
        if nargs != 1 {
            return None;
        }
        let key = strip_template_args(&ms.qualified_name);
        let d = db.decls.get(&key)?.iter().find(|d| d.params.len() == 1 && d.inline_body.is_some())?;
        let p = d.params[0].name.clone()?;
        let toks: Vec<&str> = d.inline_body.as_deref()?.split_whitespace().collect();
        let field = match toks.as_slice() {
            [f, "=", x, ";"] if *x == p => f.to_string(),
            ["this", "->", f, "=", x, ";"] if *x == p => f.to_string(),
            _ => return None,
        };
        let c = sig::find_class(db, cls)?;
        let f = c.fields.iter().find(|f| f.name == field && f.bitfield.is_none())?;
        Some((f.offset as i32, f.ty.clone()))
    }

    /// A constructor of `cls` whose initializer list sets a member directly from each parameter:
    /// (signature, member offset per parameter).
    fn member_ctor(&self, cls: &str) -> Vec<(mwdec_core::FuncSig, Vec<i32>)> {
        self.member_ctor_d(cls, 0)
    }

    fn member_ctor_d(&self, cls: &str, depth: u32) -> Vec<(mwdec_core::FuncSig, Vec<i32>)> {
        let Some(db) = self.db else { return vec![] };
        let Some(c) = sig::find_class(db, cls) else { return vec![] };
        let base = strip_template_args(cls);
        let last = sig::split_scope(&base).1.to_string();
        let mut out = vec![];
        for d in db.decls.get(&format!("{base}::{last}")).map(|v| v.as_slice()).unwrap_or(&[]) {
            if d.params.is_empty() || !d.template_params.is_empty() || d.access != mwdec_core::Access::Public {
                continue;
            }
            let Some(init) = &d.init_list else { continue };
            let names: Vec<String> = d.params.iter().map(|p| p.name.clone().unwrap_or_default()).collect();
            let mut offs: Vec<Option<i32>> = vec![None; names.len()];
            for part in sig::split_top(init, ',') {
                let toks: Vec<&str> = part.split_whitespace().collect();
                if toks.len() == 4 && toks[1] == "(" && toks[3] == ")" {
                    if let (Some(i), Some(f)) = (names.iter().position(|n| n == toks[2]), c.fields.iter().find(|f| f.name == toks[0])) {
                        offs[i] = Some(f.offset as i32);
                        continue;
                    }
                }
                // a base class or a member object constructed from parameters: its members
                if toks.len() >= 3 && toks[1] == "(" && toks.last() == Some(&")") && depth < 4 {
                    let sub = match c.bases.iter().find(|b| sig::split_scope(&strip_template_args(&b.name)).1 == toks[0]) {
                        Some(b) => Some((b.name.clone(), b.offset as i32)),
                        None => c.fields.iter().find(|f| f.name == toks[0] && f.bitfield.is_none()).and_then(|f| {
                            let ft = mwdec_lift::types::resolve(Some(db), strip_cv(&f.ty)).into_owned();
                            named(&ft).map(|n| (n.to_string(), f.offset as i32))
                        }),
                    };
                    let Some((sub_cls, sub_off)) = sub else { continue };
                    let inner = toks[2..toks.len() - 1].join(" ");
                    let bargs: Vec<String> = sig::split_top(&inner, ',').into_iter().map(|a| a.trim().to_string()).collect();
                    for (_, boffs) in self.member_ctor_d(&sub_cls, depth + 1).into_iter().filter(|(s, _)| s.params.len() == bargs.len()) {
                        for (j, a) in bargs.iter().enumerate() {
                            if let Some(i) = names.iter().position(|n| n == a) {
                                offs[i] = Some(sub_off + boffs[j]);
                            }
                        }
                        break;
                    }
                }
            }
            if offs.iter().any(|o| o.is_none()) {
                continue;
            }
            let s = mwdec_core::FuncSig {
                qualified_name: format!("{base}::{last}"),
                mangled: None,
                ret: Type::Void,
                params: d.params.iter().map(|p| mwdec_core::Param { name: p.name.clone(), ty: p.ty.clone() }).collect(),
                this_class: Some(cls.to_string()),
                is_const: false,
                is_static: false,
                is_virtual: false,
                variadic: false,
            };
            out.push((s, offs.into_iter().map(|o| o.unwrap()).collect()));
        }
        out
    }

    fn sinit_def(&mut self, g: &G, k: usize) -> Option<String> {
        let db = self.db?;
        let declared = db.globals.get(&g.symbol).cloned().or_else(|| g.dtor_class.as_ref().map(|c| (symbol_name(&g.symbol), Type::Named(c.clone()))));
        let name = match &declared {
            Some((qn, _)) => strip_unnamed_ns(qn),
            None => symbol_name(&g.symbol),
        };
        let wrap = |d: String| if g.symbol.contains("@unnamed@") { format!("namespace {{ {d} }}") } else { d };
        // one store of a whole scalar global
        let whole_scalar = match (&g.init, &declared) {
            (Init::Fields(fs), Some((_, t))) if fs.len() == 1 && fs[0].0 == 0 && !mwdec_lift::types::is_aggregate(Some(db), t) => Some(Init::Value(fs[0].2.clone())),
            (Init::Fields(fs), None)
                if fs.len() == 1
                    && fs[0].0 == 0
                    && match &g.ty {
                        Type::Unknown { size } => mwdec_lift::types::size_of(Some(db), &fs[0].1) == Some(*size),
                        Type::Array(..) => false,
                        t => !mwdec_lift::types::is_aggregate(Some(db), t),
                    } =>
            {
                Some(Init::Value(fs[0].2.clone()))
            }
            _ => None,
        };
        let init = whole_scalar.as_ref().unwrap_or(&g.init);
        match (init, &declared) {
            (Init::Ctor { sig: cs, args }, _) => {
                let t = match &declared {
                    Some((_, t)) => t.clone(),
                    None => Type::Named(cs.this_class.clone()?),
                };
                let a = self.args(args, Some(cs));
                Some(wrap(if a.is_empty() { format!("{};", decl(&t, &name)) } else { format!("{}({a});", decl(&t, &name)) }))
            }
            (Init::Value(v), Some((_, t))) => {
                let val = self.coerce(v, t);
                Some(wrap(format!("{} = {val};", decl(t, &name))))
            }
            (Init::Value(v), None) => {
                if g.registered {
                    return None;
                }
                let t = local_type(&value_type(&ty_of(v, self.vars())));
                if matches!(t, Type::Unknown { .. } | Type::Void) {
                    return None;
                }
                let val = self.expr(v, 0);
                Some(wrap(format!("{} = {val};", decl(&t, &name))))
            }
            (Init::Fields(fs), Some((_, t))) => {
                let r = mwdec_lift::types::resolve(Some(db), strip_cv(t)).into_owned();
                let cls = named(&r)?.to_string();
                for (cs, offs) in self.member_ctor(&cls) {
                    // every parameter's member is stored (the rest are the constructor's constants)
                    let vals: Option<Vec<Expr>> = offs.iter().map(|o| fs.iter().find(|(fo, _, _)| fo == o).map(|(_, _, v)| v.clone())).collect();
                    let Some(vals) = vals else { continue };
                    let a = self.args(&vals, Some(&cs));
                    return Some(wrap(format!("{}({a});", decl(t, &name))));
                }
                // a default constructor (setting the members itself)
                let base = strip_template_args(&cls);
                let last = sig::split_scope(&base).1.to_string();
                if db.decls.get(&format!("{base}::{last}")).is_some_and(|ds| ds.iter().any(|d| d.params.is_empty())) {
                    return Some(wrap(format!("{};", decl(t, &name))));
                }
                None
            }
            (Init::Fields(fs), None) => {
                if g.registered {
                    return None;
                }
                // a stand-in class: one member per stored offset, a constructor setting them
                let mut fs: Vec<&(i32, Type, Expr)> = fs.iter().collect();
                fs.sort_by_key(|f| f.0);
                let size = match &g.ty {
                    Type::Unknown { size } => *size as i32,
                    t => mwdec_lift::types::size_of(Some(db), t).map(|s| s as i32).unwrap_or(0),
                };
                let sname = format!("__mwdec_sinit_{k}");
                let mut members = vec![];
                let mut params = vec![];
                let mut inits = vec![];
                let mut vals = vec![];
                let mut at = 0i32;
                for (n, (o, t, v)) in fs.iter().enumerate() {
                    let t = local_type(&value_type(t));
                    let sz = mwdec_lift::types::size_of(Some(db), &t)? as i32;
                    if *o < at || sz == 0 {
                        return None;
                    }
                    if *o > at {
                        members.push(format!("unsigned char _p{n}[{}];", o - at));
                    }
                    members.push(format!("{};", decl(&t, &format!("m{n}"))));
                    params.push(decl(&t, &format!("a{n}")));
                    inits.push(format!("m{n}(a{n})"));
                    vals.push(self.coerce(v, &t));
                    at = o + sz;
                }
                if size > at {
                    members.push(format!("unsigned char _p[{}];", size - at));
                }
                let def = format!("struct {sname} {{ {} {sname}({}) : {} {{}} }};", members.join(" "), params.join(", "), inits.join(", "));
                self.type_defs.push(def);
                Some(wrap(format!("{sname} {name}({});", vals.join(", "))))
            }
        }
    }
}
