//! Static initializers. `__sinit_<file>_cpp` is generated by the compiler from the dynamic
//! initializations of the unit's globals, in definition order: constructor calls (plus
//! `__register_global_object` for destructors), stores of computed values, and the member stores
//! of inlined constructors. Its draft is therefore not a function but those definitions:
//! `T g(args);` / `T g = value;`. Globals the context doesn't declare (file-local objects) get a
//! stand-in class with a constructor taking each stored member.

use super::*;
use std::collections::HashMap;

enum Init {
    Ctor { sig: mwdec_core::FuncSig, args: Vec<Expr> },
    Value(Expr),
    /// (offset, access type, value) per stored member
    Fields(Vec<(i32, Type, Expr)>),
    /// an array of class objects (`__construct_array`): (element class, count)
    Array(String, u32),
}

struct G {
    symbol: String,
    /// the IR's type for the global as a whole (its extent when the context doesn't declare it)
    ty: Type,
    init: Init,
    registered: bool,
    /// class of the destructor registered for it (its type, when the context doesn't say)
    dtor_class: Option<String>,
}

fn each_stmt(body: &[Stmt], f: &mut dyn FnMut(&Stmt)) {
    for s in body {
        f(s);
        match s {
            Stmt::If { then, els, .. } => {
                each_stmt(then, f);
                each_stmt(els, f);
            }
            Stmt::While { body, .. } | Stmt::DoWhile { body, .. } => each_stmt(body, f),
            Stmt::For { init, step, body, .. } => {
                each_stmt(init, f);
                each_stmt(step, f);
                each_stmt(body, f);
            }
            Stmt::Switch { cases, .. } => {
                for c in cases {
                    each_stmt(&c.body, f);
                }
            }
            _ => {}
        }
    }
}

fn strip_casts(e: &Expr) -> &Expr {
    match e {
        Expr::Cast { e, .. } => strip_casts(e),
        e => e,
    }
}

/// (global symbol, byte offset) a pointer expression points at.
fn global_ptr(e: &Expr) -> Option<(String, Type, i32)> {
    match e {
        Expr::AddrOf(x) => global_lvalue(x).map(|(s, t, o, _)| (s, t, o)),
        Expr::Cast { e, .. } => global_ptr(e),
        // an untyped buffer's name is its address
        Expr::Global { symbol, ty } => Some((symbol.clone(), ty.clone(), 0)),
        _ => None,
    }
}

/// (global symbol, its type, offset, access type) of an lvalue inside a global.
fn global_lvalue(e: &Expr) -> Option<(String, Type, i32, Type)> {
    match e {
        Expr::Global { symbol, ty } => Some((symbol.clone(), ty.clone(), 0, ty.clone())),
        Expr::Member { base, offset, ty } => global_lvalue(base).map(|(s, gt, o, _)| (s, gt, o + offset, ty.clone())),
        Expr::Load { base, offset, ty } => global_ptr(base).map(|(s, gt, o)| (s, gt, o + offset, ty.clone())),
        _ => None,
    }
}

impl<'a> Em<'a> {
    /// The definitions a static initializer comes from, or None when its body has a shape this
    /// doesn't handle.
    pub(crate) fn sinit_defs(&mut self) -> Option<String> {
        let ir = self.ir;
        if !ir.symbol.starts_with("__sinit_") || self.opts.c_mode {
            return None;
        }
        let db = self.db?;
        if let Some(d) = self.sinit_string_object() {
            return Some(d);
        }
        if let Some(d) = self.sinit_pooled_objects() {
            return Some(d);
        }
        if let Some(d) = self.sinit_ref_literal_object() {
            return Some(d);
        }
        // single-definition register locals are inlined into the values
        let mut defs: HashMap<VarId, Expr> = HashMap::new();
        let mut ndefs: HashMap<VarId, usize> = HashMap::new();
        for s in &ir.body {
            match s {
                // (register locals and stack spill slots)
                Stmt::Assign { dst: Expr::Var(v), src } if matches!(ir.vars[*v].kind, VarKind::Local | VarKind::Stack { .. }) => {
                    *ndefs.entry(*v).or_default() += 1;
                    defs.insert(*v, src.clone());
                }
                // a stack temporary constructed in place: the temporary object `T(args)`
                Stmt::Expr(Expr::Call { callee: Callee::Method { sig: cs, this, .. }, args, .. }) if sig::is_ctor(cs) && matches!(&**this, Expr::AddrOf(x) if matches!(&**x, Expr::Var(v) if matches!(ir.vars[*v].kind, VarKind::Stack { .. }))) => {
                    let Expr::AddrOf(x) = &**this else { unreachable!() };
                    let Expr::Var(v) = &**x else { unreachable!() };
                    *ndefs.entry(*v).or_default() += 1;
                    defs.insert(*v, Expr::Construct { class: Type::Named(cs.this_class.clone()?), ctor: Some(cs.clone()), args: args.clone() });
                }
                Stmt::Assign { .. } | Stmt::Expr(_) | Stmt::Return(None) | Stmt::Comment(_) => {}
                _ => return None,
            }
        }
        if ndefs.values().any(|&n| n > 1) {
            return None;
        }
        fn subst(e: &Expr, defs: &HashMap<VarId, Expr>, depth: u32) -> Option<Expr> {
            if depth > 8 {
                return None;
            }
            let mut out = e.clone();
            let mut ok = true;
            out.rewrite(&mut |x| {
                if let Expr::Var(v) = x {
                    match defs.get(v).map(|d| subst(d, defs, depth + 1)) {
                        Some(Some(r)) => *x = r,
                        _ => ok = false,
                    }
                }
            });
            ok.then_some(out)
        }
        let mut gs: Vec<G> = vec![];
        let at = |gs: &mut Vec<G>, sym: &str, ty: &Type, init: Init| -> Option<()> {
            match gs.iter_mut().find(|g| g.symbol == sym) {
                None => {
                    gs.push(G { symbol: sym.to_string(), ty: ty.clone(), init, registered: false, dtor_class: None });
                    Some(())
                }
                Some(g) => match (&mut g.init, init) {
                    (Init::Fields(fs), Init::Fields(mut more)) => {
                        fs.append(&mut more);
                        Some(())
                    }
                    _ => None,
                },
            }
        };
        for s in &ir.body {
            match s {
                Stmt::Assign { dst: Expr::Var(_), .. } | Stmt::Return(None) | Stmt::Comment(_) => {}
                Stmt::Expr(Expr::Call { callee: Callee::Method { this, .. }, .. }) if matches!(&**this, Expr::AddrOf(x) if matches!(&**x, Expr::Var(v) if defs.contains_key(v))) => {}
                // the destructor of a static array is registered as a generated function
                // (`__arraydtor$12`) with a null object
                Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) if symbol == "__register_global_object" && matches!(args.first(), Some(Expr::Int { value: 0, .. })) => {}
                Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) if symbol == "__construct_array" && args.len() == 5 => {
                    let (g, gt, off) = global_ptr(&args[0])?;
                    fn func_addr(e: &Expr) -> Option<&str> {
                        match e {
                            Expr::FuncAddr { symbol } => Some(symbol),
                            Expr::Cast { e, .. } => func_addr(e),
                            _ => None,
                        }
                    }
                    let cls = sig::sig_of(func_addr(&args[1])?, Some(db)).this_class?;
                    let Expr::Int { value: n, .. } = strip_casts(&args[4]) else { return None };
                    if off != 0 || *n <= 0 {
                        return None;
                    }
                    at(&mut gs, &g, &gt, Init::Array(cls, *n as u32))?;
                    gs.iter_mut().find(|x| x.symbol == g)?.registered = true;
                }
                Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) if symbol == "__register_global_object" => {
                    let (g, _, _) = args.first().and_then(global_ptr)?;
                    fn func_addr(e: &Expr) -> Option<&str> {
                        match e {
                            Expr::FuncAddr { symbol } => Some(symbol),
                            Expr::Cast { e, .. } => func_addr(e),
                            _ => None,
                        }
                    }
                    let dc = args.get(1).and_then(func_addr).filter(|s| s.starts_with("__dt__")).and_then(|s| sig::sig_of(s, Some(db)).this_class);
                    let x = gs.iter_mut().find(|x| x.symbol == g)?;
                    x.registered = true;
                    x.dtor_class = dc;
                }
                Stmt::Expr(Expr::Call { callee: Callee::Method { sig: ms, this, .. }, args, .. }) => {
                    let (g, gt, off) = global_ptr(this)?;
                    let args: Vec<Expr> = args.iter().map(|a| subst(a, &defs, 0)).collect::<Option<_>>()?;
                    if sig::is_ctor(ms) && off == 0 {
                        at(&mut gs, &g, &gt, Init::Ctor { sig: ms.clone(), args })?;
                    } else {
                        // an inline setter (`SetX(v)`: `mX = x ;`): a member store
                        let cls = ms.this_class.clone()?;
                        let (foff, fty) = self.setter_field(&cls, ms, args.len())?;
                        at(&mut gs, &g, &gt, Init::Fields(vec![(off + foff, fty, args[0].clone())]))?;
                    }
                }
                Stmt::Assign { dst, src } => {
                    let (g, gt, off, ty) = global_lvalue(dst)?;
                    let v = subst(src, &defs, 0)?;
                    // (a store of the whole global is a store at offset 0 too: it may be the
                    // first member of an object, `*(float*)&v = x`)
                    let gt = if matches!(dst, Expr::Global { .. }) { self.gtypes.get(&g).cloned().unwrap_or(gt) } else { gt };
                    at(&mut gs, &g, &gt, Init::Fields(vec![(off, ty, v)]))?;
                }
                _ => return None,
            }
        }
        if gs.is_empty() {
            return None;
        }
        // a value reading another global defined here that the context doesn't declare would
        // need a declaration before its definition
        let defined: Vec<String> = gs.iter().map(|g| g.symbol.clone()).collect();
        let mut reads_own = false;
        for g in &gs {
            let vals: Vec<&Expr> = match &g.init {
                Init::Ctor { args, .. } => args.iter().collect(),
                Init::Value(v) => vec![v],
                Init::Fields(fs) => fs.iter().map(|(_, _, v)| v).collect(),
                Init::Array(..) => vec![],
            };
            for v in vals {
                v.walk(&mut |x| {
                    if let Expr::Global { symbol, .. } = x {
                        // (an object's own address is in scope in its initializer)
                        if defined.contains(symbol) && !db.globals.contains_key(symbol) && *symbol != g.symbol {
                            reads_own = true;
                        }
                    }
                });
            }
        }
        if reads_own {
            return None;
        }
        // definition order: the compiler's stores of one object end in definition order (the
        // first stores of several objects may be scheduled together)
        let mut last: HashMap<String, usize> = HashMap::new();
        for (i, s) in ir.body.iter().enumerate() {
            Stmt::walk_exprs(std::slice::from_ref(s), &mut |x| {
                if let Expr::Global { symbol, .. } = x {
                    last.insert(symbol.clone(), i);
                }
            });
        }
        gs.sort_by_key(|g| last.get(&g.symbol).copied().unwrap_or(0));
        let mut out = String::new();
        for (k, g) in gs.iter().enumerate() {
            let mut d = self.sinit_def(g, k)?;
            if self.opts.sinit_const && !db.globals.contains_key(&g.symbol) && !d.starts_with("const ") {
                d = match d.strip_prefix("namespace { ") {
                    Some(r) => format!("namespace {{ const {r}"),
                    None => format!("const {d}"),
                };
            }
            out.push_str(&d);
            out.push('\n');
        }
        Some(out)
    }

    /// File-local static objects the compiler pools into one local block (`@N`: a destructor
    /// chain node before each object): each registered object `static T x;`, its class from the
    /// registered destructor (stand-ins for classes of the unit's anonymous namespace), built by
    /// its default constructor (whose inlined stores the body holds).
    fn sinit_pooled_objects(&mut self) -> Option<String> {
        let ir = self.ir;
        let db = self.db?;
        let mut defs: HashMap<VarId, Expr> = HashMap::new();
        for s in &ir.body {
            if let Stmt::Assign { dst: Expr::Var(v), src } = s {
                if defs.insert(*v, src.clone()).is_some() {
                    return None;
                }
            }
        }
        // (pooled symbol, byte offset) a pointer expression points at
        fn ptr(e: &Expr, defs: &HashMap<VarId, Expr>, depth: u32) -> Option<(String, i32)> {
            if depth > 8 {
                return None;
            }
            match e {
                Expr::Var(v) => ptr(defs.get(v)?, defs, depth + 1),
                Expr::Cast { e, .. } => ptr(e, defs, depth + 1),
                Expr::Binary { op: BinOp::Add, l, r, .. } => {
                    let (s, o) = ptr(l, defs, depth + 1)?;
                    Some((s, o + i32::try_from(r.as_int()?).ok()?))
                }
                Expr::Global { symbol, .. } => Some((symbol.clone(), 0)),
                Expr::AddrOf(x) => lval(x, defs, depth + 1),
                _ => None,
            }
        }
        fn lval(e: &Expr, defs: &HashMap<VarId, Expr>, depth: u32) -> Option<(String, i32)> {
            match e {
                Expr::Global { symbol, .. } => Some((symbol.clone(), 0)),
                Expr::Member { base, offset, .. } => lval(base, defs, depth + 1).map(|(s, o)| (s, o + offset)),
                Expr::Load { base, offset, .. } => ptr(base, defs, depth + 1).map(|(s, o)| (s, o + offset)),
                _ => None,
            }
        }
        fn func_addr(e: &Expr) -> Option<&str> {
            match e {
                Expr::FuncAddr { symbol } => Some(symbol),
                Expr::Cast { e, .. } => func_addr(e),
                _ => None,
            }
        }
        let mut pool: Option<String> = None;
        let mut objs: Vec<(i32, String)> = vec![];
        for s in &ir.body {
            match s {
                Stmt::Assign { dst: Expr::Var(_), .. } | Stmt::Return(None) | Stmt::Comment(_) => {}
                Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) if symbol == "__register_global_object" && args.len() == 3 => {
                    let (sym, off) = ptr(&args[0], &defs, 0)?;
                    let (nsym, noff) = ptr(&args[2], &defs, 0)?;
                    let dtor = func_addr(&args[1]).filter(|d| d.starts_with("__dt__"))?;
                    let cls = sig::sig_of(dtor, Some(db)).this_class?;
                    // (the chain node right before the object)
                    if !sym.starts_with('@') || nsym != sym || noff >= off || pool.as_ref().is_some_and(|p| *p != sym) {
                        return None;
                    }
                    pool = Some(sym);
                    objs.push((off, cls));
                }
                // the inlined default constructors' stores
                Stmt::Assign { dst, .. } => {
                    let (sym, _) = lval(dst, &defs, 0)?;
                    if pool.as_ref().is_some_and(|p| *p != sym) || !sym.starts_with('@') {
                        return None;
                    }
                }
                _ => return None,
            }
        }
        let pool = pool?;
        // every store lands in a registered object
        for s in &ir.body {
            if let Stmt::Assign { dst, .. } = s {
                if matches!(dst, Expr::Var(_)) {
                    continue;
                }
                let (sym, off) = lval(dst, &defs, 0)?;
                if sym != pool || !objs.iter().any(|(o, _)| off >= *o) {
                    return None;
                }
            }
        }
        objs.sort_by_key(|o| o.0);
        // classes of the unit's anonymous namespace the context can't name: empty stand-ins
        let mut standins: Vec<String> = vec![];
        for (_, cls) in &objs {
            let mut rest = cls.as_str();
            while let Some(p) = rest.find("@unnamed@") {
                let after = &rest[p + 9..];
                let Some(e) = after.find("@::") else { break };
                let name: String = after[e + 3..].chars().take_while(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
                if !name.is_empty() && sig::find_class(db, &name).is_none() && !standins.contains(&name) {
                    standins.push(name);
                }
                rest = &after[e + 3..];
            }
        }
        let mut out = String::new();
        for n in &standins {
            out.push_str(&format!("namespace {{ struct {n} {{ }}; }}
"));
        }
        for (k, (_, cls)) in objs.iter().enumerate() {
            out.push_str(&format!("static {} sObject{k};
", strip_unnamed_ns(cls)));
        }
        Some(out)
    }


    /// One file-static object the context can't name (`lbl_...`), built by an inlined
    /// constructor whose parameters are references to const: the constant arguments live in
    /// compiler literals (`@684`) the body reads. Its class is the context's class of that size
    /// with such a constructor taking as many references as literals read:
    /// `static CMaterialList sObject(EMaterialTypes(59), EMaterialTypes(60));`. The k-th such
    /// constructor for the draft variant k.
    fn sinit_ref_literal_object(&mut self) -> Option<String> {
        let db = self.db?;
        let ir = self.ir;
        let mut lits: Vec<String> = vec![];
        let mut target: Option<String> = None;
        let mut extent = 0i32;
        let unnamed = |s: &str| (s.starts_with("lbl_") || s.starts_with('@')) && !db.globals.contains_key(s);
        let mut ok = true;
        each_stmt(&ir.body, &mut |st| match st {
            Stmt::Assign { dst, src } => {
                src.walk(&mut |x| {
                    if let Expr::Global { symbol, .. } = x {
                        if ir.literal_bytes.iter().chain(ir.temp_bytes.iter()).any(|(n, b)| n == symbol && b.len() == 4) {
                            if !lits.contains(symbol) {
                                lits.push(symbol.clone());
                            }
                        } else if !target.as_ref().is_some_and(|t| t == symbol) {
                            ok = false;
                        }
                    }
                });
                match dst {
                    Expr::Var(_) => {}
                    _ => match global_lvalue(dst) {
                        Some((g, _, off, t)) if unnamed(&g) && target.as_ref().is_none_or(|x| *x == g) => {
                            extent = extent.max(off + mwdec_lift::types::size_of(Some(db), &t).unwrap_or(4) as i32);
                            target = Some(g);
                        }
                        _ => ok = false,
                    },
                }
            }
            Stmt::Return(None) | Stmt::Comment(_) => {}
            _ => ok = false,
        });
        let g = target?;
        if !ok || lits.is_empty() || extent <= 0 {
            return None;
        }
        let vals: Vec<i64> = lits
            .iter()
            .map(|l| {
                let b = &ir.literal_bytes.iter().chain(ir.temp_bytes.iter()).find(|(n, _)| n == l).unwrap().1;
                i32::from_be_bytes([b[0], b[1], b[2], b[3]]) as i64
            })
            .collect();
        // (references to const of an enum or integer)
        let const_ref_scalar = |t: &Type| match strip_cv(t) {
            Type::Ref(x) => match &**x {
                Type::Const(y) => {
                    let r = mwdec_lift::types::resolve(Some(db), y).into_owned();
                    mwdec_lift::types::is_enum(Some(db), &r) || matches!(r, Type::Int { .. })
                }
                _ => false,
            },
            _ => false,
        };
        let mut cands: Vec<(String, Vec<Type>)> = vec![];
        for c in db.classes.values() {
            if c.size as i32 != extent || c.is_declaration || c.name.contains('<') {
                continue;
            }
            let last = sig::split_scope(&c.name).1.to_string();
            for d in db.decls.get(&format!("{}::{last}", c.name)).into_iter().flatten() {
                if d.params.len() == lits.len() && d.template_params.is_empty() && d.params.iter().all(|p| const_ref_scalar(&p.ty)) {
                    cands.push((c.name.clone(), d.params.iter().map(|p| p.ty.clone()).collect()));
                }
            }
        }
        cands.sort_by(|a, b| a.0.cmp(&b.0));
        let (cls, ptys) = cands.get(self.opts.sinit_variant.saturating_sub(1) as usize)?.clone();
        let args: Vec<String> = ptys
            .iter()
            .zip(&vals)
            .map(|(t, v)| {
                let inner = match strip_cv(t) {
                    Type::Ref(x) => strip_cv(x).clone(),
                    t => t.clone(),
                };
                format!("{}({v})", type_str(&inner))
            })
            .collect();
        let _ = g;
        Some(format!("static {} sObject0({});
", type_str(&Type::Named(cls)), args.join(", ")))
    }

    /// The member an inline setter of `cls` stores its argument into: (offset, type).
    fn setter_field(&self, cls: &str, ms: &mwdec_core::FuncSig, nargs: usize) -> Option<(i32, Type)> {
        let db = self.db?;
        if nargs != 1 {
            return None;
        }
        let key = strip_template_args(&ms.qualified_name);
        let d = db.decls.get(&key)?.iter().find(|d| d.params.len() == 1 && d.inline_body.is_some())?;
        let p = d.params[0].name.clone()?;
        let toks: Vec<&str> = d.inline_body.as_deref()?.split_whitespace().collect();
        let field = match toks.as_slice() {
            [f, "=", x, ";"] if *x == p => f.to_string(),
            ["this", "->", f, "=", x, ";"] if *x == p => f.to_string(),
            _ => return None,
        };
        let c = sig::find_class(db, cls)?;
        let f = c.fields.iter().find(|f| f.name == field && f.bitfield.is_none())?;
        Some((f.offset as i32, f.ty.clone()))
    }

    /// A constructor of `cls` whose initializer list sets a member directly from each parameter:
    /// (signature, member offset per parameter).
    fn member_ctor(&self, cls: &str) -> Vec<(mwdec_core::FuncSig, Vec<i32>)> {
        self.member_ctor_d(cls, 0)
    }

    fn member_ctor_d(&self, cls: &str, depth: u32) -> Vec<(mwdec_core::FuncSig, Vec<i32>)> {
        let Some(db) = self.db else { return vec![] };
        let Some(c) = sig::find_class(db, cls) else { return vec![] };
        let base = strip_template_args(cls);
        let last = sig::split_scope(&base).1.to_string();
        let mut out = vec![];
        for d in db.decls.get(&format!("{base}::{last}")).map(|v| v.as_slice()).unwrap_or(&[]) {
            if d.params.is_empty() || !d.template_params.is_empty() || d.access != mwdec_core::Access::Public {
                continue;
            }
            let Some(init) = &d.init_list else { continue };
            let names: Vec<String> = d.params.iter().map(|p| p.name.clone().unwrap_or_default()).collect();
            let mut offs: Vec<Option<i32>> = vec![None; names.len()];
            for part in sig::split_top(init, ',') {
                let toks: Vec<&str> = part.split_whitespace().collect();
                if toks.len() == 4 && toks[1] == "(" && toks[3] == ")" {
                    if let (Some(i), Some(f)) = (names.iter().position(|n| n == toks[2]), c.fields.iter().find(|f| f.name == toks[0])) {
                        offs[i] = Some(f.offset as i32);
                        continue;
                    }
                }
                // a base class or a member object constructed from parameters: its members
                if toks.len() >= 3 && toks[1] == "(" && toks.last() == Some(&")") && depth < 4 {
                    let sub = match c.bases.iter().find(|b| sig::split_scope(&strip_template_args(&b.name)).1 == toks[0]) {
                        Some(b) => Some((b.name.clone(), b.offset as i32)),
                        None => c.fields.iter().find(|f| f.name == toks[0] && f.bitfield.is_none()).and_then(|f| {
                            let ft = mwdec_lift::types::resolve(Some(db), strip_cv(&f.ty)).into_owned();
                            named(&ft).map(|n| (n.to_string(), f.offset as i32))
                        }),
                    };
                    let Some((sub_cls, sub_off)) = sub else { continue };
                    let inner = toks[2..toks.len() - 1].join(" ");
                    let bargs: Vec<String> = sig::split_top(&inner, ',').into_iter().map(|a| a.trim().to_string()).collect();
                    for (_, boffs) in self.member_ctor_d(&sub_cls, depth + 1).into_iter().filter(|(s, _)| s.params.len() == bargs.len()) {
                        for (j, a) in bargs.iter().enumerate() {
                            if let Some(i) = names.iter().position(|n| n == a) {
                                offs[i] = Some(sub_off + boffs[j]);
                            }
                        }
                        break;
                    }
                }
            }
            if offs.iter().any(|o| o.is_none()) {
                continue;
            }
            let s = mwdec_core::FuncSig {
                qualified_name: format!("{base}::{last}"),
                mangled: None,
                ret: Type::Void,
                params: d.params.iter().map(|p| mwdec_core::Param { name: p.name.clone(), ty: p.ty.clone() }).collect(),
                this_class: Some(cls.to_string()),
                is_const: false,
                is_static: false,
                is_virtual: false,
                variadic: false,
                runs_code: false,
            };
            out.push((s, offs.into_iter().map(|o| o.unwrap()).collect()));
        }
        out
    }

    /// One registered object built from a string literal by an inlined constructor that measures
    /// it (a loop): `T g("literal");` with `T`'s constructor from a character pointer.
    fn sinit_string_object(&mut self) -> Option<String> {
        let db = self.db?;
        let ir = self.ir;
        let mut has_loop = false;
        let mut regs: Vec<(String, String)> = vec![];
        let mut strs: Vec<Vec<u8>> = vec![];
        fn func_addr(e: &Expr) -> Option<&str> {
            match e {
                Expr::FuncAddr { symbol } => Some(symbol),
                Expr::Cast { e, .. } => func_addr(e),
                _ => None,
            }
        }
        each_stmt(&ir.body, &mut |s| {
            if matches!(s, Stmt::While { .. } | Stmt::DoWhile { .. } | Stmt::For { .. }) {
                has_loop = true;
            }
            if let Stmt::Expr(Expr::Call { callee: Callee::Direct { symbol, .. }, args, .. }) = s {
                if symbol == "__register_global_object" {
                    if let (Some((g, _, 0)), Some(d)) = (args.first().and_then(global_ptr), args.get(1).and_then(func_addr)) {
                        regs.push((g, d.to_string()));
                    }
                }
            }
        });
        Stmt::walk_exprs(&ir.body, &mut |x| {
            if let Expr::Str { bytes } = x {
                if !strs.contains(bytes) {
                    strs.push(bytes.clone());
                }
            }
        });
        let ([(g, dtor)], [lit], true) = (regs.as_slice(), strs.as_slice(), has_loop) else { return None };
        let cls = sig::sig_of(dtor, Some(db)).this_class?;
        let base = strip_template_args(&cls);
        let last = sig::split_scope(&base).1.to_string();
        let char_ptr = |t: &Type| matches!(strip_cv(t), Type::Ptr(x) if matches!(strip_cv(x), Type::Char | Type::Int { size: 1, .. } | Type::WChar | Type::Int { size: 2, .. }) || matches!(strip_cv(x), Type::Named(n) if n.contains("CharTp") || n == "T"));
        // the constructor was inlined (the loop is its own): an inline one taking the pointer,
        // other parameters being tag objects (`basic_string(literal_t, const char*)`)
        let d = db.decls.get(&format!("{base}::{last}"))?.iter().find(|d| d.is_inline_defined && d.params.iter().filter(|p| char_ptr(&p.ty)).count() == 1)?;
        let mut args = vec![];
        for p in &d.params {
            if char_ptr(&p.ty) {
                args.push(float::c_string(lit));
                continue;
            }
            let Type::Named(tag) = strip_cv(&p.ty) else { return None };
            let tag = strip_template_args(tag);
            let q = if tag.contains("::") { tag.clone() } else { format!("{}::{tag}", types::split_closers(&cls)) };
            let tc = sig::find_class(db, &q).or_else(|| sig::find_class(db, &tag))?;
            if !tc.fields.is_empty() {
                return None;
            }
            args.push(format!("{q}()"));
        }
        let (name, t) = match db.globals.get(g) {
            Some((qn, t)) => (strip_unnamed_ns(qn), t.clone()),
            None => (symbol_name(g), Type::Named(cls.clone())),
        };
        let konst = if self.opts.sinit_const && !db.globals.contains_key(g) { "const " } else { "" };
        let d = format!("{konst}{}({});", decl(&t, &name), args.join(", "));
        Some(if g.contains("@unnamed@") { format!("namespace {{ {d} }}
") } else { format!("{d}
") })
    }

    /// A static member function returning the static member `symbol` (`static const T& X() {
    /// return sX; }`): (`Class::X`, T).
    fn static_accessor(&self, symbol: &str) -> Option<(String, Type)> {
        let db = self.db?;
        let (qn, ty) = db.globals.get(symbol).cloned().or_else(|| {
            let s = sig::demangle(symbol)?;
            Some((s, Type::Unknown { size: 0 }))
        })?;
        let (cls, field) = sig::split_scope(&qn);
        let cls = cls?.to_string();
        let body = format!("return {field} ;");
        let prefix = format!("{}::", strip_template_args(&cls));
        for (k, ds) in db.decls.range(prefix.clone()..) {
            let Some(m) = k.strip_prefix(&prefix) else { break };
            if m.contains("::") {
                continue;
            }
            if let Some(d) = ds.iter().find(|d| d.is_static && d.params.is_empty() && d.inline_body.as_deref() == Some(body.as_str())) {
                let pt = match strip_cv(&d.ret) {
                    Type::Ref(x) => strip_cv(x).clone(),
                    _ => continue,
                };
                let _ = &ty;
                return Some((format!("{cls}::{m}"), pt));
            }
        }
        None
    }

    /// `class D : public B { public: virtual ~D(); <B's pure virtuals, declared>; };` for an object
    /// of the undeclared class `dc` whose stores are only vtable pointers (B's, then D's).
    fn vtable_stand_in(&mut self, dc: &str, fs: &[(i32, Type, Expr)]) -> Option<()> {
        let db = self.db?;
        let mut base: Option<String> = None;
        for (off, _, v) in fs {
            let mut vt = None;
            v.walk(&mut |x| {
                if let Expr::Global { symbol, .. } = x {
                    if let Some(c) = symbol.strip_prefix("__vt__") {
                        vt = Some(c.to_string());
                    }
                }
            });
            let vt = vt?;
            if *off != 0 {
                return None;
            }
            // `__vt__15IWeaponRenderer` -> `IWeaponRenderer` (a plain class name)
            let digits: String = vt.chars().take_while(|c| c.is_ascii_digit()).collect();
            let cls = vt[digits.len()..].to_string();
            if digits.parse::<usize>().ok() != Some(cls.len()) {
                return None;
            }
            if cls != dc && base.is_none() {
                base = Some(cls);
            }
        }
        let base = base?;
        sig::find_class(db, &base)?;
        let mut members = vec![format!("virtual ~{dc}();")];
        for (k, ds) in db.decls.range(format!("{base}::")..) {
            let Some(m) = k.strip_prefix(&format!("{base}::")) else { break };
            if m.contains("::") || m.starts_with('~') {
                continue;
            }
            for d in ds.iter().filter(|d| d.is_pure) {
                let ps: Vec<String> = d.params.iter().map(|p| type_str(&p.ty)).collect();
                members.push(format!("virtual {} {m}({}){};", type_str(&d.ret), ps.join(", "), if d.is_const { " const" } else { "" }));
            }
        }
        self.type_defs.push(format!("class {dc} : public {base} {{
public:
    {}
}};", members.join("
    ")));
        Some(())
    }

    /// Many stores of one scalar type packed from offset 0: a constructor setting them all is
    /// too big to inline (MWCC calls it), so the object is an array of a small element class
    /// (`T a[n] = { T(x, y, z), ... };`, the element constructor inlined per element). Floats
    /// group in threes or fours (vectors), otherwise the largest group that still inlines.
    fn sinit_stand_in_array(&mut self, sname: &str, name: &str, fs: &[&(i32, Type, Expr)], size: i32) -> Option<String> {
        // (members an inlined constructor may set: one more is called out of line)
        const MAX_INLINE_MEMBERS: usize = 13;
        let n = fs.len();
        if n <= MAX_INLINE_MEMBERS || std::env::var_os("MWDEC_NO_SINIT_ARRAYS").is_some() {
            return None;
        }
        let db = self.db?;
        let t = local_type(&value_type(&fs[0].1));
        let sz = mwdec_lift::types::size_of(Some(db), &t)? as i32;
        if sz == 0 || size != n as i32 * sz || !matches!(t, Type::Int { .. } | Type::Float { .. }) {
            return None;
        }
        if fs.iter().enumerate().any(|(i, (o, ft, _))| *o != i as i32 * sz || local_type(&value_type(ft)) != t) {
            return None;
        }
        let float = matches!(t, Type::Float { .. });
        let per = [3usize, 4]
            .into_iter()
            .filter(|_| float)
            .find(|g| n % g == 0)
            .or_else(|| (2..=MAX_INLINE_MEMBERS).rev().find(|g| n % g == 0))?;
        let members: Vec<String> = (0..per).map(|i| format!("{};", decl(&t, &format!("m{i}")))).collect();
        let params: Vec<String> = (0..per).map(|i| decl(&t, &format!("a{i}"))).collect();
        let inits: Vec<String> = (0..per).map(|i| format!("m{i}(a{i})")).collect();
        self.type_defs.push(format!("struct {sname} {{ {} {sname}({}) : {} {{}} }};", members.join(" "), params.join(", "), inits.join(", ")));
        let elems: Vec<String> = fs
            .chunks(per)
            .map(|c| {
                let vals: Vec<String> = c.iter().map(|(_, _, v)| self.coerce(v, &t)).collect();
                format!("{sname}({})", vals.join(", "))
            })
            .collect();
        Some(format!("{sname} {name}[{}] = {{ {} }};", n / per, elems.join(", ")))
    }

    fn sinit_def(&mut self, g: &G, k: usize) -> Option<String> {
        let db = self.db?;
        let declared = db.globals.get(&g.symbol).cloned().or_else(|| g.dtor_class.as_ref().map(|c| (symbol_name(&g.symbol), Type::Named(c.clone()))));
        let name = match &declared {
            Some((qn, _)) => strip_unnamed_ns(qn),
            None => symbol_name(&g.symbol),
        };
        let wrap = |d: String| if g.symbol.contains("@unnamed@") { format!("namespace {{ {d} }}") } else { d };
        // an object of a class the context doesn't have (defined in the unit), whose inlined
        // constructor only stores vtable pointers: a stand-in derived from the first vtable's class
        if let (Some(dc), Init::Fields(fs)) = (&g.dtor_class, &g.init) {
            if sig::find_class(db, dc).is_none() && !dc.contains("::") && !dc.contains('<') {
                return self.vtable_stand_in(dc, fs).map(|()| wrap(format!("{dc} {name};")));
            }
        }
        // one store of a whole scalar global
        let whole_scalar = match (&g.init, &declared) {
            (Init::Fields(fs), Some((_, t))) if fs.len() == 1 && fs[0].0 == 0 && !mwdec_lift::types::is_aggregate(Some(db), t) => Some(Init::Value(fs[0].2.clone())),
            (Init::Fields(fs), None)
                if fs.len() == 1
                    && fs[0].0 == 0
                    && match &g.ty {
                        Type::Unknown { size } => mwdec_lift::types::size_of(Some(db), &fs[0].1) == Some(*size),
                        Type::Array(..) => false,
                        t => !mwdec_lift::types::is_aggregate(Some(db), t),
                    } =>
            {
                Some(Init::Value(fs[0].2.clone()))
            }
            _ => None,
        };
        let init = whole_scalar.as_ref().unwrap_or(&g.init);
        match (init, &declared) {
            (Init::Array(cls, n), _) => {
                let t = match &declared {
                    Some((_, t @ Type::Array(..))) => t.clone(),
                    _ => Type::Array(Box::new(Type::Named(cls.clone())), *n),
                };
                Some(wrap(format!("{};", decl(&t, &name))))
            }
            (Init::Ctor { sig: cs, args }, _) => {
                let t = match &declared {
                    Some((_, t)) => t.clone(),
                    None => Type::Named(cs.this_class.clone()?),
                };
                let a = self.args(args, Some(cs));
                Some(wrap(if a.is_empty() { format!("{};", decl(&t, &name)) } else { format!("{}({a});", decl(&t, &name)) }))
            }
            (Init::Value(v), Some((_, t))) => {
                let val = self.coerce(v, t);
                Some(wrap(format!("{} = {val};", decl(t, &name))))
            }
            (Init::Value(v), None) => {
                if g.registered {
                    return None;
                }
                let t = local_type(&value_type(&ty_of(v, self.vars())));
                if matches!(t, Type::Unknown { .. } | Type::Void) {
                    return None;
                }
                // the address of a static object is a constant (no initializer code): stored
                // here, it came through a function, e.g. the class's static accessor
                if let Expr::AddrOf(x) = strip_casts(v) {
                    if let Expr::Global { symbol, .. } = &**x {
                        if let Some((acc, pt)) = self.static_accessor(symbol) {
                            return Some(wrap(format!("{} = &{acc}();", decl(&Type::Ptr(Box::new(Type::Const(Box::new(pt)))), &name))));
                        }
                    }
                }
                let val = self.expr(v, 0);
                Some(wrap(format!("{} = {val};", decl(&t, &name))))
            }
            (Init::Fields(fs), Some((_, t))) => {
                let r = mwdec_lift::types::resolve(Some(db), strip_cv(t)).into_owned();
                let cls = named(&r)?.to_string();
                for (cs, offs) in self.member_ctor(&cls) {
                    // every parameter's member is stored (the rest are the constructor's constants)
                    let vals: Option<Vec<Expr>> = offs.iter().map(|o| fs.iter().find(|(fo, _, _)| fo == o).map(|(_, _, v)| v.clone())).collect();
                    let Some(vals) = vals else { continue };
                    let a = self.args(&vals, Some(&cs));
                    return Some(wrap(format!("{}({a});", decl(t, &name))));
                }
                let base = strip_template_args(&cls);
                let last = sig::split_scope(&base).1.to_string();
                // (alternative drafts) the k-th constructor taking one scalar per stored member,
                // the stored values in member order (`CColor c(0xffffff7f)` whose inline body
                // sets the members itself)
                if self.opts.sinit_variant > 0 {
                    let mut fs: Vec<&(i32, Type, Expr)> = fs.iter().collect();
                    fs.sort_by_key(|f| f.0);
                    let scalar = |t: &Type| {
                        let r = mwdec_lift::types::resolve(Some(db), strip_cv(t)).into_owned();
                        !matches!(r, Type::Ref(_) | Type::Ptr(_)) && !mwdec_lift::types::is_aggregate(Some(db), &r)
                    };
                    let ctors: Vec<&mwdec_core::DeclInfo> = db
                        .decls
                        .get(&format!("{base}::{last}"))
                        .map(|v| v.iter().filter(|d| d.params.len() == fs.len() && d.template_params.is_empty() && d.access == mwdec_core::Access::Public && d.params.iter().all(|p| scalar(&p.ty))).collect())
                        .unwrap_or_default();
                    if let Some(d) = ctors.get(self.opts.sinit_variant as usize - 1) {
                    let cs = mwdec_core::FuncSig {
                        qualified_name: format!("{base}::{last}"),
                        mangled: None,
                        ret: Type::Void,
                        params: d.params.iter().map(|p| mwdec_core::Param { name: p.name.clone(), ty: p.ty.clone() }).collect(),
                        this_class: Some(cls.clone()),
                        is_const: false,
                        is_static: false,
                        is_virtual: false,
                        variadic: false,
                        runs_code: false,
                    };
                    let vals: Vec<Expr> = fs.iter().map(|f| f.2.clone()).collect();
                    let a = self.args(&vals, Some(&cs));
                    return Some(wrap(format!("{}({a});", decl(t, &name))));
                    }
                }
                // a default constructor (setting the members itself)
                if db.decls.get(&format!("{base}::{last}")).is_some_and(|ds| ds.iter().any(|d| d.params.is_empty())) {
                    return Some(wrap(format!("{};", decl(t, &name))));
                }
                // an object with a destructor whose (inlined) constructor takes no arguments that
                // we can see: default construction (its parameters may all have defaults, or
                // the constructor is the implicit one)
                if g.registered || db.decls.get(&format!("{base}::{last}")).is_none() {
                    return Some(wrap(format!("{};", decl(t, &name))));
                }
                None
            }
            (Init::Fields(fs), None) => {
                if g.registered {
                    return None;
                }
                // a stand-in class: one member per stored offset, a constructor setting them
                let mut fs: Vec<&(i32, Type, Expr)> = fs.iter().collect();
                fs.sort_by_key(|f| f.0);
                let size = match &g.ty {
                    Type::Unknown { size } => *size as i32,
                    t => mwdec_lift::types::size_of(Some(db), t).map(|s| s as i32).unwrap_or(0),
                };
                let sname = format!("__mwdec_sinit_{k}");
                if let Some(d) = self.sinit_stand_in_array(&sname, &name, &fs, size) {
                    return Some(wrap(d));
                }
                let mut members = vec![];
                let mut params = vec![];
                let mut inits = vec![];
                let mut vals = vec![];
                let mut at = 0i32;
                for (n, (o, t, v)) in fs.iter().enumerate() {
                    let t = local_type(&value_type(t));
                    let sz = mwdec_lift::types::size_of(Some(db), &t)? as i32;
                    if *o < at || sz == 0 {
                        return None;
                    }
                    if *o > at {
                        members.push(format!("unsigned char _p{n}[{}];", o - at));
                    }
                    members.push(format!("{};", decl(&t, &format!("m{n}"))));
                    params.push(decl(&t, &format!("a{n}")));
                    inits.push(format!("m{n}(a{n})"));
                    vals.push(self.coerce(v, &t));
                    at = o + sz;
                }
                if size > at {
                    members.push(format!("unsigned char _p[{}];", size - at));
                }
                let def = format!("struct {sname} {{ {} {sname}({}) : {} {{}} }};", members.join(" "), params.join(", "), inits.join(", "));
                self.type_defs.push(def);
                Some(wrap(format!("{sname} {name}({});", vals.join(", "))))
            }
        }
    }
}
